# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
    url: smtp://smtp.maap.io:525?encryption=tls&auth_mode=login&username=fc39e69c00b4e8&password=918b915095d687