# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
    url: smtp://smtp.mailtrap.io:2525?encryption=tls&auth_mode=login&username=a01278339e03ac&password=079e3d0a3a9a8b